collections_config:
  # posts:
  #   add_options:
  #     - name: Add Post
  #       editor: content
  #       schema: post
  #     - name: Add Draft
  #       editor: content
  #       collection: drafts
  #       schema: draft
  #   schemas:
  #     default:
  #       path: schemas/post.md
  #   _inputs:
  #     date:
  #       instance_value: NOW
  resource_pages:
    schemas:
      default:
        name: 'Resources page'
        path: schemas/resource.md
        icon: 'Menu Book'
