data_config:
  langs: true
  en.region: true
collection_groups:
  - heading: "Let's blog!"
    collections:
      - posts
      - drafts
  - heading: People
    collections:
      - authors
  - heading: EN Pages
    collections:
      - en_pages
collections_config:
  authors:
    schemas:
      default:
        name: 'Author page'
        path: schemas/author.md
    icon: save_as
  posts:
    schemas:
      default:
        name: 'Post page'
        path: schemas/post.md
        icon: 'Menu Book'
    _inputs:
      date:
        comment: Post date
        instance_value: NOW
      layout:
        hidden: true
      lang:
        type: select
        options:
          values: data.langs
      en_region:
        type: select
        options:
          values: data.en.region
      cta:
        label: CTA
        comment: A CTA group field
      cta.title:
        label: Title
        comment: The CTA's title
      cta.text:
        label: Text
        comment: The CTA's text
        type: markdown
  drafts:
    schemas:
      default:
        name: 'Draft Post page'
        path: schemas/draft.md
        icon: 'Menu Book'
  en_pages:
    name: EN pages
    path: en
