data_config: true
collection_groups:
  - heading: "Let's blog!"
    collections:
      - posts
      - drafts
  - heading: People
    collections:
      - authors
  - heading: Pages
    collections:
      - pages
  - heading: EN Pages
    collections:
      - en_pages
  - heading: Data
    collections:
      - en_data
  - heading: Learn
    collections:
      - learn_en
collections_config:
  en_region:
    path: _data/en/region.yml
  authors:
    schemas:
      default:
        name: 'Author page'
        path: schemas/author.md
    icon: save_as
    _inputs:
      name:
        comment: 'The full name please'
  en_data:
    path: _data/en
  posts:
    schemas:
      default:
        name: 'Post page'
        path: schemas/post.md
        icon: 'Menu Book'
    _inputs:
      date:
        comment: Post date
        instance_value: NOW
      layout:
        hidden: true
      lang:
        type: select
        options:
          values: data.langs
      en_region:
        type: select
        options:
          values: data.en.region
      cta:
        label: CTA
        comment: A CTA group field
      cta.title:
        label: Title
        comment: The CTA's title
      cta.text:
        label: Text
        comment: The CTA's text
        type: markdown
  drafts:
    schemas:
      default:
        name: 'Draft Post page'
        path: schemas/draft.md
        icon: 'Menu Book'
  en_pages:
    name: EN pages
    path: en
  learn_en:
    name: Learn EN
    path: learn
    schemas:
      default:
        name: 'Learn page'
        path: schemas/vocabulary.md
        icon: 'school'
        hide_extra_inputs: true
    # _inputs:
    #   target_lang:
    #     type: select
    #     options:
    #       values: data.target_langs