_editables:
  text:
    italic: true
  block:
    format: p h3
    undo: true
    redo: true
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: true
    embed: true
    horizontalrule: true
    image: true
    table: true
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
    styles: /css/editor.css
    left: align-left
    center: align-center
    right: align-right
    justify: align-justify
    image_size_attributes: true
    snippet: true
commit_templates:
  - template_string: "{message|trim}"
paths:
  uploads: assets/images
  dam_uploads: raw
data_config: true
main_content:
  _inputs:
    content:
      type: markdown
      options:
        table: true
        undo: true
        redo: true
    show_it:
      type: switch
_structures:
  author_info:
    values:
      - value:
          lan:
          bio:
        _inputs:
          bio:
            type: markdown
            comment: Your bio please.
  banner_items:
    values:
      - value:
          lang:
          enable:
          text:
          mobile_text:
        _inputs:
          enable:
            type: switch
          text:
            type: markdown
          mobile_text:
            type: markdown
  methods_items:
    values:
      - value:
          title:
          text:
        _inputs:
          text:
            type: markdown
            comment: Item Desc Space
  test_cats_items:
    values:
      - value:
          title:
          text:
        _inputs:
          text:
            type: markdown
            comment: Cat Desc
collection_groups:
  - heading: "Let's blog!"
    collections:
      - posts
      - drafts
  - heading: People
    collections:
      - authors
  - heading: Pages
    collections:
      - pages
  - heading: EN Pages
    collections:
      - en_pages
  - heading: Data
    collections:
      - data
      - banners_data
  - heading: All data
    collections:
      - learn_en
  - heading: Assets
    collections:
      - the_media
collections_config:
  pages:
    path: '/'
    schemas:
      default:
        path: schemas/page.md
      learn_index:
        path: schemas/learn-index.md
    filter:
      base: none
      include:
        - about.markdown
    _inputs:
      content:
        type: markdown
        options:
          table: true
          undo: true
          redo: true
  authors:
    schemas:
      default:
        name: 'Author page'
        path: schemas/author.md
    icon: save_as
    _inputs:
      name:
        comment: 'The full name please'
      person:
        type: array
        options:
          structures: _structures.author_info
  en_data:
    path: _data/en
  banners_data:
    name: 'Banners Data'
    path: _data/banner
    schemas:
      banner_schema:
        path: schemas/objects-data.md
    filter:
      base: none
    include:
      - objects.yml
    _inputs:
      show:
        type: switch
        comment: Show it or not
      settings.global_enable:
        type: switch
        comment: Global switch
      languages:
        type: array
        options:
          structures: _structures.banner_items
  the_media:
    name: Media
    path: assets
  posts:
    schemas:
      default:
        name: 'Post page'
        path: schemas/post.md
        icon: 'Menu Book'
    _inputs:
      date:
        comment: Post date
        instance_value: NOW
      layout:
        hidden: true
      lang:
        type: select
        options:
          values: data.langs
      en_region:
        type: select
        options:
          values: data.en_regions
      cta:
        label: CTA
        comment: A CTA group field
      cta.title:
        label: Title
        comment: The CTA's title
      cta.text:
        label: Text
        comment: The CTA's text
        type: markdown
  drafts:
    schemas:
      default:
        name: 'Draft Post page'
        path: schemas/draft.md
        icon: 'Menu Book'
  en_pages:
    name: EN pages
    path: en
  learn_en:
    name: Learn EN
    path: learn
    schemas:
      default:
        name: 'Learn page'
        path: schemas/vocabulary.md
        icon: 'school'
        hide_extra_inputs: true
      learn_index:
        path: schemas/learn-index.md
    _inputs:
      header:
        hidden: true
      layout:
        type: select
        options:
          values:
            - page
            - post
      desc:
        type: text
        comment: 'This is the decription'
      target_lang:
        type: select
        options:
          values: data.target_langs
      cats:
        type: select
        options:
          values: data.en_cats
      person:
        type: array
        options:
          structures: _structures.author_info
  data:
    name: All data
    schemas:
      default:
        test_categories:
          path: schemas/categories.md
      banner_schema:
        path: schemas/objects-data.md
    _inputs:
      test_categories:
        type: array
        options:
          structures: _structures.test_cats_items
