data_config: true

_structures:
  author_info:
    values:
      - value:
          name:
          bio:
        _inputs:
          bio:
            type: markdown
            comment: Your bio please.
  methods_items:
    values:
      - value:
          title:
          text:
        _inputs:
          text:
            type: markdown
            comment: Item Desc Space
collection_groups:
  - heading: "Let's blog!"
    collections:
      - posts
      - drafts
  - heading: People
    collections:
      - authors
  - heading: Pages
    collections:
      - pages
  - heading: EN Pages
    collections:
      - en_pages
  - heading: Data
    collections:
      - en_data
      - categories
  - heading: Learn
    collections:
      - learn_en
collections_config:
  pages:
    path: '/'
    schemas:
      default:
        path: schemas/page.md
      learn_index:
        path: schemas/learn-index.md
    filter:
      base: none
      include:
        - about.markdown
  authors:
    schemas:
      default:
        name: 'Author page'
        path: schemas/author.md
    icon: save_as
    _inputs:
      name:
        comment: 'The full name please'
      person:
        type: array
        options:
          structures: _structures.author_info
  en_data:
    path: _data/en
  posts:
    schemas:
      default:
        name: 'Post page'
        path: schemas/post.md
        icon: 'Menu Book'
    _inputs:
      date:
        comment: Post date
        instance_value: NOW
      layout:
        hidden: true
      lang:
        type: select
        options:
          values: data.langs
      en_region:
        type: select
        options:
          values: data.en_regions
      cta:
        label: CTA
        comment: A CTA group field
      cta.title:
        label: Title
        comment: The CTA's title
      cta.text:
        label: Text
        comment: The CTA's text
        type: markdown
  drafts:
    schemas:
      default:
        name: 'Draft Post page'
        path: schemas/draft.md
        icon: 'Menu Book'
  en_pages:
    name: EN pages
    path: en
  learn_en:
    name: Learn EN
    path: learn
    schemas:
      default:
        name: 'Learn page'
        path: schemas/vocabulary.md
        icon: 'school'
        hide_extra_inputs: true
      learn_index:
        path: schemas/learn-index.md
    _inputs:
      header:
        hidden: true
      layout:
        type: select
        options:
          values:
            - page
            - post
      desc:
        type: text
        comment: 'This is the decription'
      target_lang:
        type: select
        options:
          values: data.target_langs
      cats:
        type: select
        options:
          values: data.en_cats
      person:
        type: array
        options:
          structures: _structures.author_info
  categories:
    name: Categories
    schemas:
      default:
        path: schemas/categories.md
    _inputs:
        title:
          comment: 'This is the title'

    # _inputs:
    #   target_lang:
    #     type: select
    #     options:
    #       values: data.target_langs