collection_groups:
  - heading: "Let's blog!"
    collections:
      - posts
      - drafts
  - heading: People
    collections:
      - authors
collections_config:
  authors:
    schemas:
      default:
        name: 'Author page'
        path: schemas/author.md
        icon: 'Menu Book'
  posts:
    schemas:
      default:
        name: 'Post page'
        path: schemas/post.md
        icon: 'Menu Book'
  drafts:
    schemas:
      default:
        name: 'Draft Post page'
        path: schemas/draft.md
        icon: 'Menu Book'
