collections_config:
  posts:
    schemas:
      default:
        path: schemas/post.md
    _inputs:
      date:
        instance_value: NOW
  resource_pages:
    schemas:
      default:
        name: 'Resources page'
        path: schemas/resource.md
        icon: 'Menu Book'
