collections_config:
  posts:
    icon: book
    add_options:
      - name: Add Post
        editor: content
        collection: posts    
      - name: Add Draft
        editor: content
        collection: draft
    schemas:
      default:
        path: schemas/post.md
    _inputs:
      date:
        instance_value: NOW        

    